// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies
// this chapter never lets you spare (mercy cheats are hidden for them)
function scr_drcheat_nospare()
{
    return [
        52, // obj_dojo_spareenemy (Jigsaw Joe): mercy-lock
        3, // obj_dummyenemy (Dummy): no-mercy
        60, // obj_elnina_enemy (Elnina): no-mercy
        104, // obj_knight_enemy (): no-mercy
        61, // obj_lanino_enemy (Lanino): no-mercy
        105, // obj_tenna_board4_enemy (Tenna): no-mercy
        103, // obj_tenna_enemy (Tenna): no-mercy
        -1
    ];
}
