// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies
// this chapter never lets you spare (mercy cheats are hidden for them)
function scr_drcheat_nospare()
{
    return [
        115, // obj_blue_enemy (Blue): no-mercy
        52, // obj_dojo_spareenemy (?): mercy-lock
        116, // obj_yellow_enemy (Yellow): no-mercy
        -1
    ];
}
