// gen_nospare.csx - classify every battle enemy of this chapter: can SPARE ever work on it?
// Writes DR_OUT_DIR\gml_GlobalScript_scr_drcheat_nospare.gml (list used by CheatMenu) and prints a table.
//
// An enemy counts as "can't be spared" when the game itself gives no way to reach a spare:
//   spare-exit : its SPARE event (Other_20) is just `exit;`
//   mercy-lock : its Step event forces mercy back to 0 outside any ACT branch
//   no-mercy   : its sparepoint is 0 and none of its own code ever raises its mercy
using System.Linq;
using System.Text.RegularExpressions;
EnsureDataLoaded();
var ctx = new GlobalDecompileContext(Data);
string D(string n)
{
    var c = Data.Code.ByName(n);
    if (c == null) return null;
    try { return new Underanalyzer.Decompiler.DecompileContext(ctx, c, Data.ToolInfo.DecompilerSettings).DecompileToString(); } catch { return null; }
}
string outDir = Environment.GetEnvironmentVariable("DR_OUT_DIR");

// monstertype -> (name, sparepoint) from scr_monstersetup
var setup = D("gml_GlobalScript_scr_monstersetup") ?? "";
var blocks = Regex.Split(setup, @"(?=if \(global\.monstertype\[myself\] == \d+\))");
var typeInfo = new Dictionary<string, (string name, int spare)>();
foreach (var b in blocks)
{
    var t = Regex.Match(b, @"^if \(global\.monstertype\[myself\] == (\d+)\)");
    if (!t.Success) continue;
    var nm = Regex.Match(b, @"monstername\[myself\] = (?:stringsetloc|scr_84_get_lang_string)\(""([^""]*)""");
    var sp = Regex.Match(b, @"sparepoint\[myself\] = (-?\d+)");
    typeInfo[t.Groups[1].Value] = (nm.Success ? nm.Groups[1].Value : "?", sp.Success ? int.Parse(sp.Groups[1].Value) : -1);
}
// object -> monstertype from the encounter table
var enc = D("gml_GlobalScript_scr_encountersetup") ?? "";
var objType = new SortedDictionary<string, string>();
foreach (Match m in Regex.Matches(enc, @"monsterinstancetype\[(\d)\] = (\w+);\s*global\.monstertype\[\1\] = (\d+);"))
    if (Data.GameObjects.ByName(m.Groups[2].Value) != null) objType[m.Groups[2].Value] = m.Groups[3].Value;

// battle-controller endings that fire on mercy (Spamton NEO: mercy > 99 -> peaceful ending)
string ctl = string.Join("\n", Data.Code.Where(c => c.ParentEntry == null && c.Name.Content.StartsWith("gml_Object_obj_battlecontroller_")).Select(c => D(c.Name.Content) ?? ""));
var blocked = new List<string>();
foreach (var (obj, type) in objType)
{
    var codes = Data.Code.Where(c => c.ParentEntry == null && c.Name.Content.StartsWith($"gml_Object_{obj}_")).ToList();
    string all = string.Join("\n", codes.Select(c => D(c.Name.Content) ?? ""));
    string spare = D($"gml_Object_{obj}_Other_20");
    string step = D($"gml_Object_{obj}_Step_0") ?? "";
    var reasons = new List<string>();
    bool mercyEnding = ctl.Contains($"global.mercymod[{obj}.myself]");
    if (spare != null && Regex.IsMatch(spare.Trim(), @"^exit;?$") && !mercyEnding) reasons.Add("spare-exit");
    // a mercy reset counts unless an ACT branch (acting/actcon/choice) is open just above it
    var lines = step.Split('\n');
    for (int i = 0; i < lines.Length; i++)
    {
        if (!Regex.IsMatch(lines[i], @"global\.mercymod\[myself\] = 0;")) continue;
        var above = string.Join("\n", lines.Skip(Math.Max(0, i - 12)).Take(Math.Min(12, i)));
        var near = string.Join("\n", lines.Skip(Math.Max(0, i - 3)).Take(Math.Min(3, i)));
        if (Regex.IsMatch(near, @"mercymod\[myself\] < 0")) continue;   // clamp, not a lock
        if (!Regex.IsMatch(above, @"acting|actcon|global\.choice|scr_mercyadd|sideb")) { reasons.Add("mercy-lock"); break; }
    }
    int raise = Regex.Matches(all, @"scr_mercyadd\(myself, (?!-)|mercymod\[myself\] \+= (?!-)|mercymod\[myself\] = (100|999|global\.mercymax)").Count;
    var info = typeInfo.TryGetValue(type, out var ti) ? ti : ("?", -1);
    if (info.Item2 == 0 && raise == 0) reasons.Add("no-mercy");
    int mentions = Regex.Matches(all, @"mercy", RegexOptions.IgnoreCase).Count;
    Console.WriteLine($"[NS] {(reasons.Count > 0 ? "BLOCK" : "ok   ")} mercyrefs={mentions,-3} type={type,-3} {obj,-32} '{info.Item1}' sparepoint={info.Item2} raises={raise} {string.Join(",", reasons)}");
    if (reasons.Count > 0) blocked.Add($"{type}, // {obj} ({info.Item1}): {string.Join(", ", reasons)}");
}
if (!string.IsNullOrEmpty(outDir))
{
    Directory.CreateDirectory(outDir);
    File.WriteAllText(Path.Combine(outDir, "gml_GlobalScript_scr_drcheat_nospare.gml"),
        "// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies\n" +
        "// this chapter never lets you spare (mercy cheats are hidden for them)\n" +
        "function scr_drcheat_nospare()\n{\n    return [\n        " + string.Join("\n        ", blocked) + "\n        -1\n    ];\n}\n");
}
Console.WriteLine($"[NS] {blocked.Count} of {objType.Count} enemy objects blocked");
