// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies
// this chapter never lets you spare (mercy cheats are hidden for them)
function scr_drcheat_nospare()
{
    return [
        3, // obj_dummyenemy (scr_monstersetup_slash_scr_monstersetup_gml_59_0): no-mercy
        12, // obj_lancerboss2 (scr_monstersetup_slash_scr_monstersetup_gml_346_0): no-mercy
        18, // obj_lancerboss3 (scr_monstersetup_slash_scr_monstersetup_gml_512_0): no-mercy
        -1
    ];
}
