// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies
// this chapter never lets you spare (mercy cheats are hidden for them)
function scr_drcheat_nospare()
{
    return [
        43, // obj_berdlyb_enemy (Berdly): no-mercy
        52, // obj_dojo_spareenemy (Jigsaw Joe): mercy-lock
        3, // obj_dummyenemy (Dummy): no-mercy
        51, // obj_gigaqueen_enemy (GIGA Queen): no-mercy
        37, // obj_hatguy_enemy (Cap'n): no-mercy
        38, // obj_kk_enemy (?): no-mercy
        53, // obj_pipis_enemy (Pipis): no-mercy
        48, // obj_queen_enemy (Queen): mercy-lock, no-mercy
        39, // obj_sweet_enemy (Sweet): no-mercy
        -1
    ];
}
