// generated by CheatMenu/tools/gen_nospare.csx: global.monstertype values of enemies
// this chapter never lets you spare (mercy cheats are hidden for them)
function scr_drcheat_nospare()
{
    return [
        52, // obj_dojo_spareenemy (Jigsaw Joe): mercy-lock
        3, // obj_dummyenemy (Dummy): no-mercy
        105, // obj_hammer_of_justice_enemy (Hammer of Justice): mercy-lock, no-mercy
        107, // obj_jackenstein_enemy (Jackenstein): no-mercy
        106, // obj_sound_of_justice_enemy (???): mercy-lock, no-mercy
        36, // obj_swatchling_enemy (Swatchling): no-mercy
        108, // obj_titan_enemy (Titan): no-mercy
        109, // obj_titan_spawn_enemy (Titan Spawn): no-mercy
        -1
    ];
}
